import Head from 'next/head'
import { PostCard, PostWidget, Categories } from "../components"

export default function Home() {

  const posts = [
    {title : "nextjs app", excerpt : "learning nextjs is so awesome"},
    {title : "react framework", excerpt : "nextjs is a fullstack framework"},
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='grid grid-cols-1 lg:grid-cols-12 gap-12"'>
          <div className=' lg:col-span-8 col-span-1'>
              {
                posts.map((post, index) => (
                  <PostCard post={posts[index]} index={post.title} />
                ))
              }
          </div>
          <div className=' lg:col-span-4 col-span-1'>
              <div className=' lg:sticky relative top-8'>
                <PostWidget />
                <Categories />
              </div>
          </div>
        </div>
      </div>
    </>
  )
}

